version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: kotlin-users-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kotlin-usersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - users-network

  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kotlin-usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - users-network

volumes:
  pgdata:

networks:
  users-network:
    driver: bridge