
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kotlin-usersdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # в проде: структура проверяется, данные не меняются
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: false

# Setting up server (by default Spring Boot runs on port 8080, but we can specify it explicitly)
server:
  port: 8080

